In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [31]:
from sklearn.naive_bayes import GaussianNB
from sklearn.datasets import load_wine

In [32]:
X = load_wine()['data']
y = load_wine()['target']

In [33]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train, y_test = train_test_split(X,y)
model = GaussianNB()
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.9777777777777777

In [34]:
import sklearn
dir(sklearn.naive_bayes)
# GaussianNB
# BernoulliNB
# CategoricalNB

['ABCMeta',
 'BaseEstimator',
 'BernoulliNB',
 'CategoricalNB',
 'ClassifierMixin',
 'ComplementNB',
 'GaussianNB',
 'Hidden',
 'Integral',
 'Interval',
 'LabelBinarizer',
 'MultinomialNB',
 'Real',
 'StrOptions',
 '_BaseDiscreteNB',
 '_BaseNB',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_check_partial_fit_first_call',
 '_check_sample_weight',
 'abstractmethod',
 'binarize',
 'check_is_fitted',
 'check_non_negative',
 'label_binarize',
 'logsumexp',
 'np',
 'safe_sparse_dot',
 'warnings']

In [78]:
doc = """
(서울=연합뉴스) 전성훈 기자 = 국내 대표적인 외식 품목의 가격이 지난 4월에도 가파른 상승세를 이어갔다. 냉면은 1만1천원, 삼겹살은 2만원, 자장면은 7천원선을 위협하고 있다.

17일 한국소비자원 가격정보종합포털 '참가격'에 따르면 소비자들이 많이 찾는 8개 외식 품목의 지난달 서울지역 평균 가격이 작년보다 최고 13% 가까이 뛰었다.

가격 상승률이 가장 높은 품목은 삼계탕이었다. 지난해 4월 서울지역 평균 1만4천500원이던 삼계탕 1그릇 가격은 지난달 1만6천346원으로 12.7%나 상승했다.

자장면은 6천146원에서 6천915원으로 12.5% 올랐고, 삼겹살(200ｇ 환산 기준)은 1만7천261원에서 1만9천236원으로 11.4% 상승했다.

이밖에 김치찌개 백반(7천154원→7천769원, 8.6%↑), 김밥(2천908원→3천123원, 7.4%↑), 냉면(1만192원→1만923원, 7.2%↑), 비빔밥(9천538원→1만192원, 6.9%↑), 칼국수(8천269원→8천808원, 6.5%↑) 등 조사 대상 품목 가격이 모두 올랐다.

8개 품목 가운데 냉면, 자장면, 김치찌개 백반, 칼국수 등 4개는 지난달보다도 1∼2%씩 가격이 뛴 것으로 나타났다.

지난달 현재 1만원으로 한끼를 해결할 수 있는 외식 품목은 김치찌개 백반과 자장면, 칼국수, 김밥 등 4개에 불과하다. 지난해 4월에는 비빔밥도 포함돼 있었으나 올해 1월 1만원선을 넘으면서 빠졌다.

통계청 국가통계포털을 보면 지난달 외식 물가 지수는 117.15(2020년=100)로 전달보다 0.7% 상승했다. 2020년 12월부터 29개월간 매달 쉼 없이 올랐다.
"""

In [79]:
doc=doc.split('\n')
doc

['',
 '(서울=연합뉴스) 전성훈 기자 = 국내 대표적인 외식 품목의 가격이 지난 4월에도 가파른 상승세를 이어갔다. 냉면은 1만1천원, 삼겹살은 2만원, 자장면은 7천원선을 위협하고 있다.',
 '',
 "17일 한국소비자원 가격정보종합포털 '참가격'에 따르면 소비자들이 많이 찾는 8개 외식 품목의 지난달 서울지역 평균 가격이 작년보다 최고 13% 가까이 뛰었다.",
 '',
 '가격 상승률이 가장 높은 품목은 삼계탕이었다. 지난해 4월 서울지역 평균 1만4천500원이던 삼계탕 1그릇 가격은 지난달 1만6천346원으로 12.7%나 상승했다.',
 '',
 '자장면은 6천146원에서 6천915원으로 12.5% 올랐고, 삼겹살(200ｇ 환산 기준)은 1만7천261원에서 1만9천236원으로 11.4% 상승했다.',
 '',
 '이밖에 김치찌개 백반(7천154원→7천769원, 8.6%↑), 김밥(2천908원→3천123원, 7.4%↑), 냉면(1만192원→1만923원, 7.2%↑), 비빔밥(9천538원→1만192원, 6.9%↑), 칼국수(8천269원→8천808원, 6.5%↑) 등 조사 대상 품목 가격이 모두 올랐다.',
 '',
 '8개 품목 가운데 냉면, 자장면, 김치찌개 백반, 칼국수 등 4개는 지난달보다도 1∼2%씩 가격이 뛴 것으로 나타났다.',
 '',
 '지난달 현재 1만원으로 한끼를 해결할 수 있는 외식 품목은 김치찌개 백반과 자장면, 칼국수, 김밥 등 4개에 불과하다. 지난해 4월에는 비빔밥도 포함돼 있었으나 올해 1월 1만원선을 넘으면서 빠졌다.',
 '',
 '통계청 국가통계포털을 보면 지난달 외식 물가 지수는 117.15(2020년=100)로 전달보다 0.7% 상승했다. 2020년 12월부터 29개월간 매달 쉼 없이 올랐다.',
 '']

In [80]:
doc=doc[1:]
doc

['(서울=연합뉴스) 전성훈 기자 = 국내 대표적인 외식 품목의 가격이 지난 4월에도 가파른 상승세를 이어갔다. 냉면은 1만1천원, 삼겹살은 2만원, 자장면은 7천원선을 위협하고 있다.',
 '',
 "17일 한국소비자원 가격정보종합포털 '참가격'에 따르면 소비자들이 많이 찾는 8개 외식 품목의 지난달 서울지역 평균 가격이 작년보다 최고 13% 가까이 뛰었다.",
 '',
 '가격 상승률이 가장 높은 품목은 삼계탕이었다. 지난해 4월 서울지역 평균 1만4천500원이던 삼계탕 1그릇 가격은 지난달 1만6천346원으로 12.7%나 상승했다.',
 '',
 '자장면은 6천146원에서 6천915원으로 12.5% 올랐고, 삼겹살(200ｇ 환산 기준)은 1만7천261원에서 1만9천236원으로 11.4% 상승했다.',
 '',
 '이밖에 김치찌개 백반(7천154원→7천769원, 8.6%↑), 김밥(2천908원→3천123원, 7.4%↑), 냉면(1만192원→1만923원, 7.2%↑), 비빔밥(9천538원→1만192원, 6.9%↑), 칼국수(8천269원→8천808원, 6.5%↑) 등 조사 대상 품목 가격이 모두 올랐다.',
 '',
 '8개 품목 가운데 냉면, 자장면, 김치찌개 백반, 칼국수 등 4개는 지난달보다도 1∼2%씩 가격이 뛴 것으로 나타났다.',
 '',
 '지난달 현재 1만원으로 한끼를 해결할 수 있는 외식 품목은 김치찌개 백반과 자장면, 칼국수, 김밥 등 4개에 불과하다. 지난해 4월에는 비빔밥도 포함돼 있었으나 올해 1월 1만원선을 넘으면서 빠졌다.',
 '',
 '통계청 국가통계포털을 보면 지난달 외식 물가 지수는 117.15(2020년=100)로 전달보다 0.7% 상승했다. 2020년 12월부터 29개월간 매달 쉼 없이 올랐다.',
 '']

In [81]:
pd.Series(doc)

0     (서울=연합뉴스) 전성훈 기자 = 국내 대표적인 외식 품목의 가격이 지난 4월에도 ...
1                                                      
2     17일 한국소비자원 가격정보종합포털 '참가격'에 따르면 소비자들이 많이 찾는 8개 ...
3                                                      
4     가격 상승률이 가장 높은 품목은 삼계탕이었다. 지난해 4월 서울지역 평균 1만4천5...
5                                                      
6     자장면은 6천146원에서 6천915원으로 12.5% 올랐고, 삼겹살(200ｇ 환산 ...
7                                                      
8     이밖에 김치찌개 백반(7천154원→7천769원, 8.6%↑), 김밥(2천908원→3...
9                                                      
10    8개 품목 가운데 냉면, 자장면, 김치찌개 백반, 칼국수 등 4개는 지난달보다도 1...
11                                                     
12    지난달 현재 1만원으로 한끼를 해결할 수 있는 외식 품목은 김치찌개 백반과 자장면,...
13                                                     
14    통계청 국가통계포털을 보면 지난달 외식 물가 지수는 117.15(2020년=100)...
15                                                     
dtype: object

In [82]:
def str_split(x):
    return x.split()
doc = pd.Series(doc).apply(str_split).iloc[range(0,15,2)]

In [83]:
word_list=[]
for word in doc:
    word_list.extend(word)

In [84]:
word_list=list(set(word_list))
word_list

['1만9천236원으로',
 '지난해',
 '삼계탕',
 '6.9%↑),',
 '쉼',
 '1만6천346원으로',
 '소비자들이',
 '없이',
 '조사',
 '지난달',
 '이어갔다.',
 '서울지역',
 '12월부터',
 '8개',
 '가까이',
 '117.15(2020년=100)로',
 '기준)은',
 '29개월간',
 '빠졌다.',
 '백반,',
 '백반과',
 '기자',
 '지난',
 '나타났다.',
 '보면',
 '2만원,',
 '1만7천261원에서',
 '가격이',
 '가파른',
 '가격은',
 '비빔밥도',
 '김밥',
 '높은',
 '올랐고,',
 '17일',
 '가운데',
 '칼국수,',
 '13%',
 '삼계탕이었다.',
 '6천146원에서',
 '넘으면서',
 '1만4천500원이던',
 '국내',
 '있다.',
 '(서울=연합뉴스)',
 '있는',
 '냉면은',
 '8.6%↑),',
 '4월에는',
 '자장면은',
 '냉면(1만192원→1만923원,',
 '4월에도',
 '찾는',
 '최고',
 '칼국수',
 '12.5%',
 '비빔밥(9천538원→1만192원,',
 '4개에',
 '평균',
 '수',
 '위협하고',
 '전성훈',
 '7천원선을',
 '1만1천원,',
 '현재',
 '6.5%↑)',
 '품목은',
 '뛴',
 '상승했다.',
 '환산',
 '품목의',
 '뛰었다.',
 '1그릇',
 '11.4%',
 '등',
 '칼국수(8천269원→8천808원,',
 '4월',
 '대표적인',
 '전달보다',
 '상승세를',
 '7.2%↑),',
 '한끼를',
 '12.7%나',
 '모두',
 "'참가격'에",
 '있었으나',
 '1만원선을',
 '포함돼',
 '김치찌개',
 '해결할',
 '물가',
 '작년보다',
 '6천915원으로',
 '가격정보종합포털',
 '올해',
 '2020년',
 '가격',
 '1∼2%씩',
 '4개는',
 '품목',
 '백반(7천154원→7천769원,',
 '삼겹살은',
 '외식',
 '국가통계포털을',


In [85]:
word_dict={idx:val for idx, val in enumerate(word_list)}
word_dict

{0: '1만9천236원으로',
 1: '지난해',
 2: '삼계탕',
 3: '6.9%↑),',
 4: '쉼',
 5: '1만6천346원으로',
 6: '소비자들이',
 7: '없이',
 8: '조사',
 9: '지난달',
 10: '이어갔다.',
 11: '서울지역',
 12: '12월부터',
 13: '8개',
 14: '가까이',
 15: '117.15(2020년=100)로',
 16: '기준)은',
 17: '29개월간',
 18: '빠졌다.',
 19: '백반,',
 20: '백반과',
 21: '기자',
 22: '지난',
 23: '나타났다.',
 24: '보면',
 25: '2만원,',
 26: '1만7천261원에서',
 27: '가격이',
 28: '가파른',
 29: '가격은',
 30: '비빔밥도',
 31: '김밥',
 32: '높은',
 33: '올랐고,',
 34: '17일',
 35: '가운데',
 36: '칼국수,',
 37: '13%',
 38: '삼계탕이었다.',
 39: '6천146원에서',
 40: '넘으면서',
 41: '1만4천500원이던',
 42: '국내',
 43: '있다.',
 44: '(서울=연합뉴스)',
 45: '있는',
 46: '냉면은',
 47: '8.6%↑),',
 48: '4월에는',
 49: '자장면은',
 50: '냉면(1만192원→1만923원,',
 51: '4월에도',
 52: '찾는',
 53: '최고',
 54: '칼국수',
 55: '12.5%',
 56: '비빔밥(9천538원→1만192원,',
 57: '4개에',
 58: '평균',
 59: '수',
 60: '위협하고',
 61: '전성훈',
 62: '7천원선을',
 63: '1만1천원,',
 64: '현재',
 65: '6.5%↑)',
 66: '품목은',
 67: '뛴',
 68: '상승했다.',
 69: '환산',
 70: '품목의',
 71: '뛰었다.',
 72: '1그릇',
 73: '11.4%',
 74: '등',
 

In [86]:
dic_word = { val:idx for idx, val in word_dict.items()}
dic_word

{'1만9천236원으로': 0,
 '지난해': 1,
 '삼계탕': 2,
 '6.9%↑),': 3,
 '쉼': 4,
 '1만6천346원으로': 5,
 '소비자들이': 6,
 '없이': 7,
 '조사': 8,
 '지난달': 9,
 '이어갔다.': 10,
 '서울지역': 11,
 '12월부터': 12,
 '8개': 13,
 '가까이': 14,
 '117.15(2020년=100)로': 15,
 '기준)은': 16,
 '29개월간': 17,
 '빠졌다.': 18,
 '백반,': 19,
 '백반과': 20,
 '기자': 21,
 '지난': 22,
 '나타났다.': 23,
 '보면': 24,
 '2만원,': 25,
 '1만7천261원에서': 26,
 '가격이': 27,
 '가파른': 28,
 '가격은': 29,
 '비빔밥도': 30,
 '김밥': 31,
 '높은': 32,
 '올랐고,': 33,
 '17일': 34,
 '가운데': 35,
 '칼국수,': 36,
 '13%': 37,
 '삼계탕이었다.': 38,
 '6천146원에서': 39,
 '넘으면서': 40,
 '1만4천500원이던': 41,
 '국내': 42,
 '있다.': 43,
 '(서울=연합뉴스)': 44,
 '있는': 45,
 '냉면은': 46,
 '8.6%↑),': 47,
 '4월에는': 48,
 '자장면은': 49,
 '냉면(1만192원→1만923원,': 50,
 '4월에도': 51,
 '찾는': 52,
 '최고': 53,
 '칼국수': 54,
 '12.5%': 55,
 '비빔밥(9천538원→1만192원,': 56,
 '4개에': 57,
 '평균': 58,
 '수': 59,
 '위협하고': 60,
 '전성훈': 61,
 '7천원선을': 62,
 '1만1천원,': 63,
 '현재': 64,
 '6.5%↑)': 65,
 '품목은': 66,
 '뛴': 67,
 '상승했다.': 68,
 '환산': 69,
 '품목의': 70,
 '뛰었다.': 71,
 '1그릇': 72,
 '11.4%': 73,
 '등': 74,
 

In [87]:
import numpy as np
dtm = np.zeros((8,127))
dtm

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [88]:
doc.index = np.arange(len(doc))
doc.index

Index([0, 1, 2, 3, 4, 5, 6, 7], dtype='int32')

In [89]:
dtm = np.zeros((8,127))
for i in range(dtm.shape[0]):
    for j in range(len(doc[i])):
        dtm[i,dic_word.get(doc[i][j])] += 1
        
dtm

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 1., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [90]:
dtm[2]

array([0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0.,
       0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 0.])

In [91]:
word_dict

{0: '1만9천236원으로',
 1: '지난해',
 2: '삼계탕',
 3: '6.9%↑),',
 4: '쉼',
 5: '1만6천346원으로',
 6: '소비자들이',
 7: '없이',
 8: '조사',
 9: '지난달',
 10: '이어갔다.',
 11: '서울지역',
 12: '12월부터',
 13: '8개',
 14: '가까이',
 15: '117.15(2020년=100)로',
 16: '기준)은',
 17: '29개월간',
 18: '빠졌다.',
 19: '백반,',
 20: '백반과',
 21: '기자',
 22: '지난',
 23: '나타났다.',
 24: '보면',
 25: '2만원,',
 26: '1만7천261원에서',
 27: '가격이',
 28: '가파른',
 29: '가격은',
 30: '비빔밥도',
 31: '김밥',
 32: '높은',
 33: '올랐고,',
 34: '17일',
 35: '가운데',
 36: '칼국수,',
 37: '13%',
 38: '삼계탕이었다.',
 39: '6천146원에서',
 40: '넘으면서',
 41: '1만4천500원이던',
 42: '국내',
 43: '있다.',
 44: '(서울=연합뉴스)',
 45: '있는',
 46: '냉면은',
 47: '8.6%↑),',
 48: '4월에는',
 49: '자장면은',
 50: '냉면(1만192원→1만923원,',
 51: '4월에도',
 52: '찾는',
 53: '최고',
 54: '칼국수',
 55: '12.5%',
 56: '비빔밥(9천538원→1만192원,',
 57: '4개에',
 58: '평균',
 59: '수',
 60: '위협하고',
 61: '전성훈',
 62: '7천원선을',
 63: '1만1천원,',
 64: '현재',
 65: '6.5%↑)',
 66: '품목은',
 67: '뛴',
 68: '상승했다.',
 69: '환산',
 70: '품목의',
 71: '뛰었다.',
 72: '1그릇',
 73: '11.4%',
 74: '등',
 

In [93]:
word_dict[0]


'1만9천236원으로'

In [94]:
dic_word['(서울=연합뉴스)']

44