In [1]:
import numpy as np

In [27]:
# 전략 무
def monti():
    windows=np.arange(3) #range는 제너레이터, arange는 값
    win_window=np.random.choice(windows,1)
    user_window=np.random.choice(windows,1)
    
    if win_window == user_window:
        open_window=windows[windows != user_window][0] #아무거나 말고 그냥 첫번째거 가져와서 쓴다.
    else:
        open_window=windows[(windows != user_window) & (windows != win_window)]
    return win_window, user_window

In [39]:
monti()

(array([1]), array([0]))

In [21]:
# 3전략
def monti(strategy):
    windows=np.arange(3) #range는 제너레이터, arange는 값
    win_window=np.random.choice(windows,1)
    user_window=np.random.choice(windows,1)
    
    if win_window == user_window:
        open_window=windows[windows != user_window][0] #아무거나 말고 그냥 첫번째거 가져와서 쓴다.
    else:
        open_window=windows[(windows != user_window) & (windows != win_window)]
        
    if strategy == 'change':
        choice_window = windows[(windows != user_window) & (windows != open_window)]
    elif strategy=='random':
        choice_window = np.random.choice(windows[windows != open_window],1)
    else:
        choice_window = user_window
    return choice_window == win_window

In [22]:
s = 0
for _ in range(1000):
    s += monti('random')
s/1000

array([0.491])

In [23]:
s = 0
for _ in range(1000):
    s += monti('change')
s/1000

array([0.652])

In [25]:
score = np.random.randint(50, 101,1000)
score

array([ 65,  93,  55,  95,  93,  84,  88,  74,  77,  52,  96,  84,  71,
        96,  85,  50,  77, 100,  71, 100,  92,  76,  92,  74,  63,  76,
        86,  85,  83,  63,  90, 100,  74,  58,  91,  62,  98,  88,  94,
        90,  71,  58,  67,  88,  67,  83,  99,  97,  79,  81,  60,  60,
        93,  84,  60,  50,  52,  50,  91,  90,  71,  53,  68,  72,  95,
        99,  71,  67,  75,  98,  65,  75,  61,  58,  60,  79,  98,  53,
        86,  69,  62,  54,  92,  59,  53,  57,  87,  75,  64,  77,  70,
        79,  65,  76,  98,  80,  98,  64,  82,  59,  86,  77,  59,  99,
        60,  64,  77,  62,  57,  96,  51,  97,  69,  66,  76,  84,  84,
        63,  89, 100,  76,  71,  73,  51,  75,  58,  91,  64,  87,  99,
        76,  80,  76,  99,  73,  61,  98,  92,  50,  96,  80,  95,  90,
       100, 100,  84,  68,  70,  55,  97,  87,  82,  54,  84,  73,  63,
        76,  74,  70,  54,  69,  60,  95,  68,  81,  74,  84,  82,  53,
        79,  58,  88,  86,  98,  66,  79,  59,  78,  77,  71,  9

In [48]:
x=np.random.choice([0,1],100)

In [49]:
# 90 이상이면 A, 90 미만 80 이상이면 B, ...
score_class=[]
for s in score: # elif: exclusive 하게 들어감 
    if s >= 90: score_class.append('A')
    elif s>= 80: score_class.append('B')
    elif s>= 70: score_class.append('C')
    else: score_class.append('D')

In [50]:
bool_x = []
for i in x:
    if i == 0:
        bool_x.append(False)
    else:
        bool_x.append(True)

In [51]:
# np.where(condition, True일 때 값, False일때 값)
bool_x = np.where(x == 0, False, True)
bool_x

array([ True, False, False, False,  True,  True, False,  True, False,
       False, False,  True, False,  True, False,  True, False, False,
       False,  True, False, False,  True, False,  True, False,  True,
        True,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True, False, False,  True, False,  True,  True,
        True, False,  True, False, False, False, False, False, False,
       False,  True,  True, False,  True, False,  True, False, False,
        True,  True, False, False, False,  True, False,  True,  True,
        True,  True, False,  True,  True, False,  True,  True,  True,
        True,  True, False, False,  True,  True, False, False,  True,
        True,  True,  True,  True, False, False,  True,  True,  True,
       False])

In [52]:
bool_x=x.astype(bool)
bool_x

array([ True, False, False, False,  True,  True, False,  True, False,
       False, False,  True, False,  True, False,  True, False, False,
       False,  True, False, False,  True, False,  True, False,  True,
        True,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True, False, False,  True, False,  True,  True,
        True, False,  True, False, False, False, False, False, False,
       False,  True,  True, False,  True, False,  True, False, False,
        True,  True, False, False, False,  True, False,  True,  True,
        True,  True, False,  True,  True, False,  True,  True,  True,
        True,  True, False, False,  True,  True, False, False,  True,
        True,  True,  True,  True, False, False,  True,  True,  True,
       False])

In [54]:
# np.where이 for문보다 훨~씬 빠름
score_class=np.where(score>=90, 'A', 
                     np.where(score>=80, 'B', 
                              np.where(score>=70, 'C', 
                                       'D')))
score_class

array(['D', 'A', 'D', 'A', 'A', 'B', 'B', 'C', 'C', 'D', 'A', 'B', 'C',
       'A', 'B', 'D', 'C', 'A', 'C', 'A', 'A', 'C', 'A', 'C', 'D', 'C',
       'B', 'B', 'B', 'D', 'A', 'A', 'C', 'D', 'A', 'D', 'A', 'B', 'A',
       'A', 'C', 'D', 'D', 'B', 'D', 'B', 'A', 'A', 'C', 'B', 'D', 'D',
       'A', 'B', 'D', 'D', 'D', 'D', 'A', 'A', 'C', 'D', 'D', 'C', 'A',
       'A', 'C', 'D', 'C', 'A', 'D', 'C', 'D', 'D', 'D', 'C', 'A', 'D',
       'B', 'D', 'D', 'D', 'A', 'D', 'D', 'D', 'B', 'C', 'D', 'C', 'C',
       'C', 'D', 'C', 'A', 'B', 'A', 'D', 'B', 'D', 'B', 'C', 'D', 'A',
       'D', 'D', 'C', 'D', 'D', 'A', 'D', 'A', 'D', 'D', 'C', 'B', 'B',
       'D', 'B', 'A', 'C', 'C', 'C', 'D', 'C', 'D', 'A', 'D', 'B', 'A',
       'C', 'B', 'C', 'A', 'C', 'D', 'A', 'A', 'D', 'A', 'B', 'A', 'A',
       'A', 'A', 'B', 'D', 'C', 'D', 'A', 'B', 'B', 'D', 'B', 'C', 'D',
       'C', 'C', 'C', 'D', 'D', 'D', 'A', 'D', 'B', 'C', 'B', 'B', 'D',
       'C', 'D', 'B', 'B', 'A', 'D', 'C', 'D', 'C', 'C', 'C', 'A

In [60]:
def fibo(n):
    if n <= 1:
        return n
    return fibo(n-1) + fibo(n-2)

In [64]:
fibo(6)

8

In [68]:
# 처음 36개까지는 빠른데 그 이후부터 급 느려진다. 
# 자신의 메모리를 쓰기 때문. 
# 따라서 빨리 쓰는 법을 생각해야
for i in range(100):
    print(f'{i+1}번째 : {fibo(i)}')

1번째 : 0
2번째 : 1
3번째 : 1
4번째 : 2
5번째 : 3
6번째 : 5
7번째 : 8
8번째 : 13
9번째 : 21
10번째 : 34
11번째 : 55
12번째 : 89
13번째 : 144
14번째 : 233
15번째 : 377
16번째 : 610
17번째 : 987
18번째 : 1597
19번째 : 2584
20번째 : 4181
21번째 : 6765
22번째 : 10946
23번째 : 17711
24번째 : 28657
25번째 : 46368
26번째 : 75025
27번째 : 121393
28번째 : 196418
29번째 : 317811
30번째 : 514229
31번째 : 832040
32번째 : 1346269
33번째 : 2178309
34번째 : 3524578
35번째 : 5702887
36번째 : 9227465
37번째 : 14930352
38번째 : 24157817
39번째 : 39088169
40번째 : 63245986
41번째 : 102334155
42번째 : 165580141
43번째 : 267914296
44번째 : 433494437
45번째 : 701408733
46번째 : 1134903170
47번째 : 1836311903


KeyboardInterrupt: 

In [69]:
from functools import cache

In [70]:
@cache #데코레이터, 내가 만든 fibo 함수가 cache까지 갖고 감
def fibo(n):
    if n <= 1:
        return n
    return fibo(n-1) + fibo(n-2)

In [71]:
fibo(400) #fibo가 cache가 돼서 금방 결과가 나옴

176023680645013966468226945392411250770384383304492191886725992896575345044216019675

In [2]:
from functools import lru_cache

In [3]:
@lru_cache(maxsize=10)
def fibo(n):
    if n <= 1:
        return n
    return fibo(n-1) + fibo(n-2)

In [4]:
fibo(100)

354224848179261915075

In [7]:
fibo(400)

176023680645013966468226945392411250770384383304492191886725992896575345044216019675

In [5]:
fibo(50)

12586269025

In [9]:
for i in range(400):
    print(fibo(i))

0
1
1
2
3
5
8
13
21
34
55
89
144
233
377
610
987
1597
2584
4181
6765
10946
17711
28657
46368
75025
121393
196418
317811
514229
832040
1346269
2178309
3524578
5702887
9227465
14930352
24157817
39088169
63245986
102334155
165580141
267914296
433494437
701408733
1134903170
1836311903
2971215073
4807526976
7778742049
12586269025
20365011074
32951280099
53316291173
86267571272
139583862445
225851433717
365435296162
591286729879
956722026041
1548008755920
2504730781961
4052739537881
6557470319842
10610209857723
17167680177565
27777890035288
44945570212853
72723460248141
117669030460994
190392490709135
308061521170129
498454011879264
806515533049393
1304969544928657
2111485077978050
3416454622906707
5527939700884757
8944394323791464
14472334024676221
23416728348467685
37889062373143906
61305790721611591
99194853094755497
160500643816367088
259695496911122585
420196140727489673
679891637638612258
1100087778366101931
1779979416004714189
2880067194370816120
4660046610375530309
754011380474634642

In [17]:
from sklearn import datasets
from sklearn.datasets import load_iris

In [16]:
x=load_iris()['data']

In [18]:
from sklearn.cluster import KMeans

In [21]:
import warnings
warnings.filterwarnings('ignore')

In [22]:
km=KMeans(2)
km.fit(x)

KMeans(n_clusters=2)

In [40]:
y=km.labels_

In [24]:
from sklearn.linear_model import LogisticRegression

In [25]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [26]:
x.shape

(150, 4)

In [30]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [57]:
##1.가설함수
##2.예측값
##3.비용함수
##4.미분(수치)
##5.경사하강
##6.1~5 반복


##1.가설함수
w=np.random.(4,1)
b=0
y_hat=sigmoid(np.dot(x,w)+b)
##2.예측값
##3.비용함수
##4.미분(수치)
##5.경사하강
##6.1~5 반복

In [58]:
w

array([[-2.8806908 ],
       [ 0.94608222],
       [ 0.03961422],
       [-0.1152807 ]])

In [36]:
y_hat #0~1 사잇값(sigmoid 기능)

array([[0.99137849],
       [0.99056355],
       [0.98774884],
       [0.98860229],
       [0.99051056],
       [0.99465618],
       [0.98775203],
       [0.99140216],
       [0.98604046],
       [0.99069598],
       [0.99351875],
       [0.99056257],
       [0.98933578],
       [0.98032337],
       [0.99397729],
       [0.99482723],
       [0.99293326],
       [0.9917252 ],
       [0.99570574],
       [0.99193899],
       [0.99460483],
       [0.99237489],
       [0.98267646],
       [0.99399528],
       [0.99234326],
       [0.99243365],
       [0.99261358],
       [0.99258857],
       [0.99216765],
       [0.9900551 ],
       [0.9909643 ],
       [0.99428561],
       [0.99157495],
       [0.99311174],
       [0.99106989],
       [0.98970743],
       [0.99332822],
       [0.98927597],
       [0.98482181],
       [0.99207494],
       [0.99037552],
       [0.98785482],
       [0.98437801],
       [0.99309688],
       [0.99414862],
       [0.9901748 ],
       [0.99216684],
       [0.987

In [38]:
y_hat.shape

(150, 1)

In [41]:
y=y.reshape(-1,1)

In [46]:
def cost(w, b):
    y_hat=sigmoid(np.dot(x,w)+b)
    return np.sum(y*np.log(y_hat)+(1-y)*np.log(1-y_hat))

In [47]:
def diff(func, w, b):
    h=1e-4
    grad = np.zeros_like(w)
    for i in range(w.shape[0]):
        for j in range(w.shape[1]):
            tmp = w[i,j]
            fx=func(w,b)
            w[i,j]=tmp+h
            fxh=func(w,b)
            grad[i,j]=(fxh-fx)/h
            w[i,j]=tmp # x, y= y, x 하는 방법(copy 만들기)
    fx=func(w,b)
    fxh=func(w,b+h)
    grad_b=(fxh-fx)/h
    return grad_a, grad_b

In [48]:
lr=1e-3
epochs=10000
for _ in range(epochs):
    w -= diff(cost, w, b)[0]*lr
    b -= diff(cost, w, b)[1]*lr

TypeError: 'NoneType' object is not subscriptable

In [59]:
from sklearn.metrics import accuracy_score

In [71]:
accuracy_score(np.where(sigmoid(np.dot(x,w)+b) > .5, 1, 0),y)

0.35333333333333333

In [63]:
load_iris()['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [64]:
from sklearn.linear_model import LogisticRegression

In [65]:
model=LogisticRegression().fit(x,y)
model.score(x,y) #직접 만든 함수랑 라이브러리 함수랑 정확도 똑같음(똑같아야했음-쌤꺼랑 비교)

0.9866666666666667

In [66]:
model.predict(x)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [93]:
def cost(w, b):
    y_hat=sigmoid(np.dot(x,w)+b)
    return np.sum(y*np.log(y_hat)+(1-y)*np.log(1-y_hat))

def diff(func, w, b):
    h=1e-4
    grad_a = np.zeros_like(w)
    for i in range(w.shape[0]):
        for j in range(w.shape[1]):
            tmp = w[i,j]
            fx=func(w,b)
            w[i,j]=tmp+h
            fxh=func(w,b)
            grad_a[i,j]=(fxh-fx)/h
            w[i,j]=tmp # x, y= y, x 하는 방법(copy 만들기)
    fx=func(w,b)
    fxh=func(w,b+h)
    grad_b=(fxh-fx)/h
    return grad_a, grad_b

def sigmoid(x):
    return 1/(1+np.exp(-x))

class doggy:
    def __init__(self):
        self.w=None
        self.b=None
        print('bowwow')
        
    def fit(self, x, y):
        self.x=x
        self.y=y
        self.b=0
        self.w=np.random.randn(self.x.shape[1], self.y.shape[1])
        lr=1e-3
        y_hat=sigmoid(np.dot(self.x, self.w)+self.b)##가설함수->예측
        
        for _ in range(10000):
            self.w-=diff(cost, self.w, self.b)[0]*lr
            self.b-=diff(cost, self.w, self.b)[1]*lr
        
        return f'doggy model complete'
    def predict(self,x):
        return np.where(sigmoid(np.dot(x, self.w)+self.b) > .5, 1, 0)
    
    def score(self, x, y):
        y_hat = np.where(sigmoid(np.dot(x, self.w)+self.b) > .5, 1, 0)
        return np.around(sum(y_hat == y)/y.size, 3)
    

In [94]:
model=doggy()

bowwow


In [95]:
model.fit(load_iris()['data'], km.labels_.reshape(-1,1))

'doggy model complete'

In [96]:
model.score(load_iris()['data'], km.labels_.reshape(-1,1))

array([0.353])

In [104]:
def a_func():
    print('a function')
def b_func():
    print('b function')

In [105]:
a_func()

a function


In [106]:
b_func()

b function


In [107]:
def deco(func):
    return b_func()

In [108]:
@deco
def a_func():
    print('a function')

b function


In [111]:
a_func

In [118]:
def camelcase(x):
    return ''.join([word.capitalize() for word in x.split('_')])

In [119]:
def mapper(func):
    def wrapper(list_arg):
        return [func(word) for word in list_arg]
    return wrapper

In [120]:
@wrapper
def camelcase(x):
    return ''.join([word.capitalize() for word in x.split('_')])

NameError: name 'wrapper' is not defined

In [121]:
x=['asia_seoul', 'europe_paris', 'america_usa']
camelcase(x)

AttributeError: 'list' object has no attribute 'split'